[docs] core/document_selection.dart
superlistapp/super_editor pull request #221
Opened 2021-06-03 20:26 UTC by creativecreatorormaybenot

## Summary

As I wanted to learn about and gain a deep understanding of the `super_editor` API in general, I explored the individual parts of the source code.  
In this process, I figured it would be very useful to add public member API docs accordingly and contribute them back to the project.

### Part

In this pull request in particular, I am only adding documentation to the `core/document_selection.dart` file, exclusively. This should hopefully make it easier to review the individual parts of my contribution.

## Guidelines

Because we need to have a common standard for documentation in order to make the developer experience when researching about the API coherent, I **strictly followed** Effective Dart.  
In this case, the relevant articles are:

* [Effective Dart: Documentation](https://dart.dev/guides/language/effective-dart/documentation)
* And [Effective Dart](https://dart.dev/guides/language/effective-dart) for a general overview.

### Assertions

I do consider assertions as part of *docs* in the scope of these pull request. This is because I feel they have a documenting value and can enforce what the docs state using debug-time warnings.

### Imports

Any added imports in the docs changes have been made in order to create references to members from other files to allow the analyzer to recognize them. This is necessary for code navigation e.g.  
This means that if I added an import to `'package:super_editor/src/default_editor/text.dart'`, then this happened because `[TextNodePosition]` was referenced in the docs.

### Meta

I do think enforcing these rules to ensure coherency is important as well, which is why we should consider adding meta documentation for: how to contribute and which guidelines to follow. This might also involve adding the [`public_member_api_docs`](https://dart-lang.github.io/linter/lints/public_member_api_docs.html) lint rule.

## Full contribution

To query the related PRs that make up this effort of contributing docs, you can use [this query](https://github.com/superlistapp/super_editor/pulls?q=is%3Apr+author%3Acreativecreatorormaybenot+%22%5Bdocs%5D%22+).

### Reviews

I hope that these contributions can be merged with the existing efforts. I tried to really understand what the API does and how and why it works the way it does and why it has been designed the way it has been designed.  
Nonetheless, my documentation should of course be thoroughly reviewed. I am not sure who is best-suited for each individual review. cc @matthew-carroll @salihgueler

2021-06-05 07:59 UTC, matthew-carroll requested changes

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// Creates a selection from the [base] position and [extent] position within
I think we should change "and" to "to" because the nature of `base` and `extent` imply a direction.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// If the [base] position comes before the [extent] position within the
I think we need 3 cases here instead of 2 and blank lines between them:

If [base] equals [extent], the selection is collapsed.

If [base] comes before [extent], the selection is expanded in the downstream direction.

If [base] comes after [extent], the selection is expanded in the upstream direction.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// If the [extent] position comes before the [base] position within the
Please apply similar changes as mentioned for `base`.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// Whether this selection is collapsed or not.
To follow the style of similar doc comments elsewhere in this package, the first line should read:
Returns [true] if this selection is collapsed, or [false] if this selection is expanded.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// highlighted any node or character.
This part isn't quite accurate. Images and horizontal rules are highlighted even when the selection is collapsed because those nodes/components only have one piece of content. I think it is sufficient to say that:

A [DocumentSelection] is "collapsed" when its [base] and [extent] are equal ([DocumentPosition.==]). Otherwise, the [DocumentSelection] is "expanded".

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// If this selection is already collapsed, returns this instance (i.e. the
DocumentSelection is immutable, so I don't think we need this specification.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// Note that the relative position within the document does not play a role
We can make this more concise:
Note, the returned [DocumentSelection] is collapsed at this selection's [extent], regardless of whether this selection's [extent] comes before or after its [base].

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// If this selection is already collapsed, returns this instance (i.e. the
Similar to an earlier comment, this class is immutable, so I don't think we need this note.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// If this selection is already collapsed, returns this instance (i.e. the
Same here for removing this note.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// Creates a copy of this selection but with the given fields replaced with
I think this description can match that of `TextSelection.copy`:
Creates a new [DocumentSelection] based on the current selection, with the provided parameters overridden.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// ID that points to the single node that the selection describes about.
I think this description can be:
The ID of the node that's selected.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// The actual node-specific selection data.
This description can be:
The selection within the given node.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// Whether this node selection is base in the context of the surrounding
I think I would say:
[true] if this [DocumentNodeSelection] forms the base position of a larger document selection, false otherwise.

In the case that a document selection is limited to a single node, a [DocumentNodeSelection] will form the base position and the extent position at the same time.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// Whether this node selection is extent in the context of the surrounding
I would have this description match my suggestion above, but adjusted for the extent.

2021-06-05 07:59 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// Whether a thin selection highlight should be shown when the text is empty,
I would say:
[true] if the component rendering this [DocumentNodeSelection] should paint a highlight even when the given node has no content, [false] otherwise.

This behavior is primarily intended to coordinate small highlights in empty paragraphs when a document selection spans multiple paragraphs.

2021-06-05 09:33 UTC, creativecreatorormaybenot commented on super_editor/lib/src/core/document_selection.dart
> +  /// If the [base] position comes before the [extent] position within the
@matthew-carroll I did actually already have all three cases, however, I used the word "Otherwise` for the last case. I will change it to use "If" every time and add the new lines.

2021-06-05 09:38 UTC, creativecreatorormaybenot commented on super_editor/lib/src/core/document_selection.dart
> +  /// Whether this selection is collapsed or not.
[Effective Dart states](https://dart.dev/guides/language/effective-dart/documentation#prefer-starting-variable-getter-or-setter-comments-with-noun-phrases) otherwise:

> PREFER starting variable, getter, or setter comments with noun phrases.

Do you think I should still change it, here and elsewhere?

2021-06-05 09:49 UTC, creativecreatorormaybenot commented on super_editor/lib/src/core/document_selection.dart
> +  /// Whether this node selection is base in the context of the surrounding
About this and the two below, I saw that you used this style elsewhere in the docs, though I was not sure if everywhere.

However, it felt off to me because of https://dart.dev/guides/language/effective-dart/documentation#prefer-starting-variable-getter-or-setter-comments-with-noun-phrases.  
I also checked `flutter/flutter` code to find how it is done there and I found:  

https://github.com/flutter/flutter/blob/94a41cde83695b1267d0d7fae9d075bfd92af402/packages/flutter/lib/src/material/scaffold.dart#L2114

However, I also found some code that went along the lines of "True if ...".  So I am wondering because you have mentioned this style choice here and elsewhere: what do you think we should go with? I can update all occurrences accordingly afterwards.

2021-06-05 09:51 UTC, creativecreatorormaybenot commented
Thanks @matthew-carroll - I applied most suggestions from your code review. Now, there is only the open questions about `bool` getters. Once that is resolved, I can make any last adjustments if necessary.

2021-06-06 23:33 UTC, creativecreatorormaybenot commented
@matthew-carroll Let me know when you have made a decision on https://github.com/superlistapp/super_editor/pull/221#discussion_r645969982 - I will adjust accordingly then 👍

2021-06-12 01:13 UTC, matthew-carroll commented on super_editor/lib/src/core/document_selection.dart
> +  /// Whether this node selection is base in the context of the surrounding
@creativecreatorormaybenot let's do this, take a look at the section right above the one that you linked:
https://dart.dev/guides/language/effective-dart/documentation#prefer-starting-function-or-method-comments-with-third-person-verbs

The example they give is:
```
/// Returns `true` if every element satisfies the [predicate].
```

Let's take that approach. So in this case:

```
/// Returns `true` if this [DocumentNodeSelection] forms the base position of a larger document selection, `false` otherwise.
```

And one of these days I'll figure out the correct different between `[]` ` `` ` in these doc comments....

Let me know if you have any other questions about this.

2021-06-12 14:10 UTC, creativecreatorormaybenot commented on super_editor/lib/src/core/document_selection.dart
> +  /// Whether this node selection is base in the context of the surrounding
@matthew-carroll Thanks, makes sense 👍 

The difference between ```` and `[]` is easy: ```` is for **formatting** as code blocks and `[]` is for **linking** to references (in the IDE for code navigation and in generated docs for hyperlinks) :v:

2021-06-13 07:32 UTC, matthew-carroll approved these changes
LGTM

2021-06-13 07:32 UTC, merged