AttributedSpans equality check disregards order of attributions
superlistapp/super_editor pull request #271
Opened 2021-07-22 19:44 UTC by britannio

Closes https://github.com/superlistapp/super_editor/issues/270

2021-07-22 19:49 UTC, britannio commented
Does VSCode have a setting to format lines at 120 characters?

2021-07-22 19:50 UTC, creativecreatorormaybenot commented
@britannio it has nothing to do with VSCode. But you can change the `dart format` line wrap in settings :)

2021-07-22 20:00 UTC, britannio commented
Cool, I created https://github.com/superlistapp/super_editor/pull/272 so I don't have to run the `dart format` command manually.

2021-07-22 20:55 UTC, creativecreatorormaybenot commented
@britannio Of course not what I was suggesting :) Nice PR - I meant the user settings.

2021-09-03 02:45 UTC, matthew-carroll commented
Can you add a test to the appropriate test file that verifies unordered equality?

2021-09-03 22:06 UTC, britannio commented
@matthew-carroll Just added the tests!

2021-09-06 22:30 UTC, matthew-carroll requested changes
This is a good start on tests, but we should be more holistic with the testing range if we're going to take the time to add them.

2021-09-06 22:30 UTC, matthew-carroll commented on super_editor/test/src/infrastructure/attributed_spans_test.dart
> +      test('it determines that spans with equivalent content in a different order are equal', () {
The wording in this description is a bit passive. How about:
it is equal to another AttributedSpans with equivalent markers that are stored in a different order

2021-09-06 22:30 UTC, matthew-carroll commented on super_editor/test/src/infrastructure/attributed_spans_test.dart
> +    group('equality', () {
If we're going to write a test for different marker order, then we should probably write a test for the standard case where the marker order is the same.

Also, how about a test for empty `AttributedSpans`s?

And, when it comes to proving things, the converse is important, too. Consider writing one or more tests that demonstrate non-equality, to make sure that equality doesn't always return `true`.

2021-09-14 22:18 UTC, britannio commented
Thanks for the feedback! Hopefully, I've addressed it all.

2021-09-24 20:41 UTC, matthew-carroll commented on super_editor/test/src/infrastructure/attributed_spans_test.dart
> +      const boldStart = SpanMarker(attribution: bold, offset: 0, markerType: SpanMarkerType.start);
I'll accept this test as-is so that we can merge it, but in general I think that test configurations should go within the tests. Right now it doesn't look too bad to have these 4 properties here, but imagine that this group of tests grows to be 50 tests. How many different configurations might we have in that case? They'd all accumulate here and become a mess. So, for tests, I recommend re-stating the conditions in each test. In rare cases, you might move some of the setup generation into a method that a test invokes, but even that should be rare.

2021-09-24 20:42 UTC, matthew-carroll approved these changes
LGTM. Thanks for the implementation and for following up with tests.

2021-09-24 20:42 UTC, merged