MutableDocument equality check compares nodes of other document
superlistapp/super_editor pull request #273
Opened 2021-07-24 15:33 UTC by britannio

It was previously comparing `_nodes` with `nodes` but `nodes` is a getter that returns `_nodes` so they're identical and hence `const DeepCollectionEquality().equals(_nodes, nodes)` is always true.

This is my second PR related to misbehaving equality checks so would it be worth adding a few unit tests?

2021-09-01 07:16 UTC, matthew-carroll commented
Unit tests sound like a good idea. Would you like to add some to this PR for this change?

2021-09-01 08:19 UTC, britannio commented
> Unit tests sound like a good idea. Would you like to add some to this PR for this change?

Sure

2021-09-03 22:13 UTC, britannio commented
@matthew-carroll Just added the tests!

2021-09-06 22:24 UTC, matthew-carroll requested changes
Here are some recommendations to improve the unit tests to better communicate the purpose of the tests, and to cover more boundary conditions.

2021-09-06 22:24 UTC, matthew-carroll commented on super_editor/test/src/core/document_editor_test.dart
> +    test('it is equal to a similar document with the same content', () {
These test descriptions don't really describe what it means to be equal. Based on what I'm seeing, it looks like the description should read:

it is equal to another document when each content node is equal to the corresponding node in the other document

2021-09-06 22:24 UTC, matthew-carroll commented on super_editor/test/src/core/document_editor_test.dart
> +      final document2 = MutableDocument(nodes: [node, node]);
Tests should generally consist of situations that make sense in reality. There's no obvious situation where the same instance of a node would appear in a document, let alone back-to-back. This test should use a different node for the 2nd node in `document2`.

2021-09-06 22:24 UTC, matthew-carroll commented on super_editor/test/src/core/document_editor_test.dart
> +    test('it is NOT equal to a similar document with different content', () {
Referring to documents as "similar" is ambiguous. Similar how?

This test appears to test the following:
it is NOT equal to a document with the same starting nodes but with additional nodes at the end

2021-09-06 22:24 UTC, matthew-carroll commented on super_editor/test/src/core/document_editor_test.dart
> +
It's good to verify boundary cases and I think we're missing one here:
it is equal to another document when both documents are empty

2021-09-06 22:24 UTC, matthew-carroll commented on super_editor/test/src/core/document_editor_test.dart
> +    });
You've shown that a document with extra nodes will not be equal, but that means that an equality check could simply compare the `length` of the nodes and still pass these tests. It would be good to ensure that two lists with the same number of nodes are not equal when the nodes are not equal.

it is NOT equal to a document when corresponding nodes are NOT equal

2021-09-14 22:17 UTC, britannio commented
Thanks for the feedback! Hopefully, I've addressed it all.

2021-09-24 20:44 UTC, matthew-carroll approved these changes
LGTM. Thanks.

2021-09-24 20:44 UTC, merged