[Bugfix] Show caret on desktop/web
superlistapp/super_editor pull request #367
Opened 2021-12-14 21:22 UTC by miguelcmedeiros

Show the caret on desktop/web based on the passed or resolved value of `SuperEditor.gestureMode`.

Fixes #366

2021-12-14 22:50 UTC, matthew-carroll commented
@miguelcmedeiros can you explain what this change is meant to do? It looks like some code was moved but I'm not seeing any impactful changes.

2021-12-15 08:43 UTC, miguelcmedeiros commented
> 

In `_buildGestureSystem` we had the logic to resolve the value of `gestureMode`, and with it use the appropriate document interactor. In `_buildDocumentLayout` we were using directly `widget.mouse` instead of also resolving the correct value.

The changes in this PR are to extract the resolution logic from and reuse in both methods.

2021-12-15 22:20 UTC, matthew-carroll commented
@miguelcmedeiros how does re-use solve the caret issue? What went wrong with the caret, and how does this fix whatever went wrong?

2021-12-15 22:34 UTC, miguelcmedeiros commented on super_editor/lib/src/default_editor/super_editor.dart
> +            showCaret: _focusNode.hasFocus && _resolvedGestureMode == DocumentGestureMode.mouse,
@matthew-carroll 
If I understand the intention here, showCaret should be true if the document has focus and gestureMode is mouse. Since widget.gestureMode is by default null, then showCaret was always false. 
With the fix, the comparison will be made against widget.gestureMode (if not null) or the appropriate value for the host platform.

2021-12-18 00:45 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/super_editor.dart
> +            showCaret: _focusNode.hasFocus && _resolvedGestureMode == DocumentGestureMode.mouse,
Ok, so the root problem is that `showCaret` was getting set to `false` in some cases where we expected it to be `true`.

2021-12-18 00:47 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/super_editor.dart
> -    late DocumentGestureMode gestureMode;
Based on your latest description of the problem, that `showCaret` was sometimes `false` when it should be `true` because `widget.gestureMode` was `null`, here's what I suggest:

Bring back the if-statement. There's no need to break out a method for this. The gesture mode doesn't appear to be accessed from any place outside of `_buildGestureSystem()`.

You should be able to fix this problem by just changing `widget.gestureMode` to `gestureMode` on the `showCaret` line.

2021-12-18 00:48 UTC, matthew-carroll requested changes
Please see my earlier comment in the code.

2021-12-18 22:25 UTC, miguelcmedeiros commented on super_editor/lib/src/default_editor/super_editor.dart
> -    late DocumentGestureMode gestureMode;
`gestureMode` is accessed in `_buildGestureSystem` and `_buildDocumentLayout` (where `showCaret` is set), hence why the logic was extracted to a getter.

2021-12-18 23:31 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/super_editor.dart
> -    late DocumentGestureMode gestureMode;
It looks like GitHub collapsed the code in just the right way to make it all look like one method.

In this case, if we're going to offer a getter method to get a non-null value, then I'd like to name the getter as just `_gestureMode`. The word `resolved` tends to introduce new questions about what's being resolved, and how, and at that point the person reading the code is spending more time than before.

So the getter would be:

```dart
DocumentGestureMode get _gestureMode => [put if-statement here]
```

And I would put that getter definition above the build() methods and beneath the State lifecycle methods.

2021-12-19 08:40 UTC, miguelcmedeiros commented on super_editor/lib/src/default_editor/super_editor.dart
> -    late DocumentGestureMode gestureMode;
Done ✅

2021-12-20 01:30 UTC, matthew-carroll approved these changes
LGTM

2021-12-20 07:36 UTC, merged