Optimizing AttributedSpans.collapseSpans() to run in linear time
superlistapp/super_editor pull request #407
Opened 2022-02-02 19:12 UTC by jmatth

The current implementation of `collapseSpans` operates by pre-generating the list of start and end points for the collapsed spans, then walking that list and repeatedly checking the list of `SpanMarker`s to determine which `Attribution`s should apply to each span. In cases with many spans this causes a large amount of duplicate work, especially in cases with overlapping spans. In my testing it takes the method almost 2 seconds to return with 1000 spans. For a less contrived example, it only needs about 50 overlapping spans to take over 16ms (time for a frame when running at 60fps).

This PR:

- Changes `collapseSpans` to run with a single linear pass of the `SpanMarker` list. It also eliminates the preprocessing step of generating the start and end locations for the collapsed spans, which wasn't significantly contributing to the runtime but fewer LoC is always a nice bonus.
- Updates the sorting logic for `SpanMarker` to always have `start` markers precede `end` markers. Without this the inner loop of `collapseSpans` needs some ugly conditionals to handle an edge case where an end marker precedes a start marker with the same offset.
- Adds a couple tests to the AttributedSpans test suite for behavior that that wasn't already covered but broke tests from other parts of the library while I was working on this.
- Adds some minor additions to `MultiAttributionSpan`: `copyWith` for convenient copying, `toString` override for better log messages.

After these changes it the method takes 3ms to return with 50 spans and 30ms with 1000. I ran the tests locally via `flutter test` and everything passed.

2022-02-03 06:08 UTC, matthew-carroll requested changes
Thanks for the improvements. I added a few requests for minor changes.

2022-02-03 06:08 UTC, matthew-carroll commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +        // Merge the new attribution into the current span.
Can you change the word "merge" in this comment and the log statement to "add" so that is clearly opposes "remove" in the else statement?

2022-02-03 06:08 UTC, matthew-carroll commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +      // Because we handle committing completed spans before this, we know that by this point the current marker should
This comment is probably important, but I'm not entirely sure what it's trying to say. Can you revisit this comment and try to establish some context? The comment seems to assume that the reader already has a problem in mind, but I'm not sure what that problem is.

2022-02-03 06:08 UTC, matthew-carroll commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +      // The spans committed during the loop didn't cover the entire range.  The value in currentSpan should already
The language in this comment mixes some times and responsibilities, making it difficult to differentiate between the description of the current situation vs the description of what needs to be done. Can you revisit this comment and try to make it clear what the situation is when coming into the if-statement, vs the work that you're about to do?

2022-02-03 06:08 UTC, matthew-carroll commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +    if (collapsedSpans.isEmpty || collapsedSpans.last.end < contentLength - 1) {
Is it possible to check for the empty situation near the beginning of the method, similar to content length? Or is that calculation too difficult to do on its own?

2022-02-03 16:10 UTC, jmatth commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +        // If we encountered a start token, end the current span 1 index earlier to simulate the missing end marker.
Yeah, this is probably a quirk of the development process working its way into the comments. In an early implementation I was preprocessing the list to insert start and end markers at the points where spans overlapped. I got rid of that because 1) it's actually unnecessary and 2) it's actually harder to read and reason about. Since those explicit start/end markers aren't there, this on the fly calculation is now "simulating" them.

I agree this wording doesn't make sense now without that particular thought process. I'll update it similar to your suggestion on the end token.

2022-02-03 17:14 UTC, jmatth commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +      // Because we handle committing completed spans before this, we know that by this point the current marker should
The comment is there to say that because the way the code is ordered, by the time we reach this point we know that we can just apply changes to the current span based on the current marker without any other checks. A previous version of the code required a bounds check on the current marker's offset, and this comment came about when that check was made unnecessary and removed.

How about: `By the time we get here, we are guaranteed that the current marker should modify the current span. Apply changes based on the type of the marker.`?

2022-02-03 17:34 UTC, jmatth commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +        // If we encountered an end token, start the next span 1 index later to simulate the missing start marker.
Addressed in [this comment](https://github.com/superlistapp/super_editor/pull/407#discussion_r798726573).

2022-02-04 03:01 UTC, matthew-carroll commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +      // Because we handle committing completed spans before this, we know that by this point the current marker should
Sure, that comment makes sense

2022-02-04 03:02 UTC, matthew-carroll commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +    if (collapsedSpans.isEmpty || collapsedSpans.last.end < contentLength - 1) {
I think I'd prefer this approach. This way readers know that if they get past the guard statements, they're definitely doing some span calculations.

2022-02-04 04:59 UTC, jmatth commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +    if (collapsedSpans.isEmpty || collapsedSpans.last.end < contentLength - 1) {
Cool, taken care of in b3c9c1ee02162dd599d82821a568c042a7490af6.

2022-02-04 04:59 UTC, jmatth commented on super_editor/lib/src/infrastructure/attributed_spans.dart
> +      // Because we handle committing completed spans before this, we know that by this point the current marker should
Taken care of in f7a40f556656ae15bb4964cbb1fe7afb2f8cc931.

2022-02-04 05:00 UTC, jmatth commented
I think I've addressed all the outstanding PR comments.

2022-02-04 05:35 UTC, matthew-carroll approved these changes
LGTM. Thanks.

2022-02-04 05:35 UTC, merged