fixes for #351
superlistapp/super_editor pull request #589
Opened 2022-05-24 17:47 UTC by faithoflifedev

2022-05-24 17:48 UTC, faithoflifedev commented
@matthew-carroll  here is the draft PR for issue #351

2022-05-29 05:56 UTC, matthew-carroll commented
Hi @faithoflifedev - I'm about to look into the PR. Before I get to the code, I'll mention that PR titles and descriptions are good places to include useful information.

It would be helpful to see a title that describes what you're solving, rather than sending the reader to some issue ticket. You don't have to restate everything, but a concise synopsis is nice.

As for the PR description, that's your opportunity to prime the reader for what they're about to see in the code. How did you solve the problem? Did you hit any hurdles? Should the reader expect anything unusual? I recommend treating the PR write-up as your guide for the code that we're now reviewing.

With that, I'll look into the code...

2022-05-29 06:37 UTC, matthew-carroll requested changes
I took a first pass over the source code. I think I've probably left enough comments to make some substantial updates. I can take another look when you think it's ready.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/document_keyboard_actions.dart
> +ExecutionInstruction scrollWhenNavigationKeyPressed({
I see that other actions aren't commented. That's probably an oversight. These handlers should include clear explanation for why they exist, and what they do.

As for the name, I'm not sure that anyone is going to know what a "navigation key" is. It's probably clearer to simply list the keys that are relevant: `scrollOnPageUpPageDownHomeAndEnd()`

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/document_keyboard_actions.dart
> +  //the super_editor doesn't always have a scroll controller
I think that it always should have one, or at least always have a `ScrollPosition`. In any event, there should always be a scrollable that surrounds a document.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/document_keyboard_actions.dart
> +  //end key or fn-arrowDn (on Mac)
I see a number of comments that appear to restate the key comparison in the if-statements. I don't think these comments are telling us more than the if-statements that follow. The interesting details are where you're jumping. For example, within the first if-branch, it might nice to say `// The user pressed the END key, scroll to the bottom of the document`.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/document_keyboard_actions.dart
> +        nextJump < scrollController.position.maxScrollExtent ? nextJump : scrollController.position.maxScrollExtent;
I think this line can be replaced with a call to `min()` when you set `nextJump`. Also, it's unclear why one thing is called `nextJump` and the other is called `jumpTo`. I'm guessing you did that because you needed a temporary variable. In this case you don't a temporary variable, but if you did, it would be preferable to choose a name that explains why you need 2 variables, e.g., `scrollOffsetOnePageDown`. That name implies that there may be a difference between "one page down" and "jump to"

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/document_keyboard_actions.dart
> +    jumpTo = nextJump > 0 ? nextJump : scrollController.position.minScrollExtent;
This line can be replaced with a call to `max()` when you set `nextJump`

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/document_keyboard_actions.dart
> +  if (jumpTo != null) {
How would `jumpTo` be null?

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/super_editor.dart
> +      scrollController: widget.scrollController,
Let's pass this as the last argument, for consistency with other locations.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/super_editor.dart
> +  scrollWhenNavigationKeyPressed,
Do we want to scroll a document when there's no selection? If not, this handler should go beneath `doNothingWhenThereIsNoSelection`.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/lib/src/default_editor/super_editor.dart
> +  doNothingWhenFnKeyPressed,
Why is this handler needed? What happens if it's not here?

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +enum Extent { top, bottom, pgDown, pgUp }
I generally recommend placing all declarations after the `main()` method. When you're reading a test file, you probably don't have any context to understand these declarations because you haven't seen any of the test definitions yet. Therefore, they're just getting in the way.

They should also include doc comments, and if they're not intended to be referenced from other test files, they should be private.

With regard to naming, unless there's an overriding factor, we shouldn't abbreviate things. `pgDown` -> `pageDown`, `pgUp` -> `pageUp`. Those couple extra characters don't cost us anything, but they avoid a moment of friction when reading the code.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +    double screenWidth = 640.0;
I haven't looked at where this variable is used, yet, but any value that doesn't change should either be `const` or `final`. Any value that does change should probably not be defined outside the test that changes it.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +    Future<void> _testExtent(WidgetTester tester, Extent extent,
As I read this code from top to bottom, when I reach `_testExtent`, I have no basis to appreciate what that means. I can clean that you're probably doing something with scrolling, but I have no idea what you're testing.

As for function declarations, you should prefer each parameter on its own line, rather than a parameter list that wraps like this. Just add a `,` after the final parameter and the auto-formatter will update it.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +      final testDocument = TestDocument(tester, screenWidth: screenWidth, screenHeight: screenHeight);
We have a class called `Document` in `super_editor`, so it's not a good idea to create something called `TestDocument` if it's not a `Document`. Moreover, a `Document` in `super_editor` is a purely logical construct. It has no concept of layout or painting. So this further muddies the water by adding Flutter UI concepts into this thing called a `TestDocument`.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +      await testDocument.buildDoc();
This approach to pumping a widget tree might be reasonable, but it's unexpected. I would expect to either see a call to `tester.pumpWidget()`, or invocation of a method such as `_pumpDocumentLayout()`, which would internally configure the widget tree so that we don't need to repeat it in every test. At first glance, I don't see any benefit of baking this behavior into a special object.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +      //caret is at begining of doc
The small addition of a verb can be helpful to disambiguate a comment like this: `//caret is at beginng of doc` -> `// Ensure that the caret is at the beginning of the document`.

It's not clear why the caret should be at the beginning of the doc. Did the above `buildDoc()` method also set a selection? If so, that detail should be in the name. If you move that method to a standalone function, it might look like `_pumpDocumentLayoutWithCollapsedSelection()`. Additionally, if that method is used in many tests, there's no need to verify what the method did. If that method fails to do its job, a bunch of your tests will fail and you'll figure it out. We're more concerned with verifying intermediate and final results.

Also, please add a space after the `//` for comments.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +      if (scrollToBottom) {
Generally, tests should not contain conditional logic. You should know exactly what behavior you're running, and what results you're verifying. Is there another way to achieve your testing goals?

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +      //activate key press
This comment doesn't add anything. Mentioning what key we're pressing and/or why we're pressing it would be a much better use of a comment.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +      await tester.pumpAndSettle();
It's a good idea to explain every `pumpAndSettle()`. Ideally an action should only require a `pump()`, so if we need the "settle" then it's nice to know why.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +      switch (extent) {
At first glance, I don't like this switch statement. This forces the reader to become a human compiler and try to figure out what we're really verifying. I'd rather see 4 simple tests than 1 test with 4 switch branches.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +          //confirm no scroll beyond top
But why do we expect this? What are we testing here?

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +      //caret should not move
Why not? I've read from top to bottom of this method and I have no idea what we're testing. All I know is that some key was pressed, for some reason, and then we expect one of a set of things to have happened...or not happened, I guess.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +  group('Navigation Keys', () {
The `K` can be lowercase.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +    group('navigation', () {
I noticed that the first group is capitalized, but this group is not.

2022-05-29 06:37 UTC, matthew-carroll commented on super_editor/test/src/default_editor/navigation_keys_test.dart
> +          (tester) async => _testExtent(tester, Extent.bottom, key: LogicalKeyboardKey.pageDown, scrollToBottom: true));
I see a test here that's completely defined in terms of a configuration to some other method. This must be a common practice in other languages because I've seen this a number of times from other people. But this should never be done.

If you think about it, immediately delegating a test to some other method doesn't help the reader at all. You haven't reduced the code in the test, you've only moved it. And worse yet, the code at the destination is sure to be generalized. By definition, that `_testExtent()` method is actually many tests in one method. So the reader has to become a compiler and execute that method in his/her head. This practice breeds all sorts of mistakes and bugs and frustrations.

Instead, define one test within one test declaration. You can centralize certain pieces of tests, like an initial tree pump, when that centralization doesn't hurt the reader's ability to appreciate what's being tested, why it's being tested, and how it's being tested.

2022-06-08 00:34 UTC, faithoflifedev commented
Hi Matt,

Sorry for the delay getting to this, I had some other projects that I
needed to spend time on.  Anyway, I've been able to go through the feedback
you provided and I believe I've addressed all the items that you
identified.  The PR us available at -
https://github.com/superlistapp/super_editor/pull/608

Regards,
Chris


On Tue, May 31, 2022 at 9:27 AM Chris D ***@***.***> wrote:

> Hi Matt,
>
> Thank you for providing this feedback.  I'll start making the changes
> based on your suggestions as time permits.
>
> Chris
>
> On Sun, May 29, 2022 at 2:38 AM Matt Carroll ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> I took a first pass over the source code. I think I've probably left
>> enough comments to make some substantial updates. I can take another look
>> when you think it's ready.
>> ------------------------------
>>
>> In super_editor/lib/src/core/edit_context.dart
>> <https://github.com/superlistapp/super_editor/pull/589#discussion_r884215502>
>> :
>>
>> > @@ -17,12 +18,15 @@ class EditContext {
>>    ///
>>    /// The [documentLayout] is passed as a [getDocumentLayout] callback that
>>    /// should return the current layout as it might change.
>> -  EditContext({
>> -    required this.editor,
>> -    required DocumentLayout Function() getDocumentLayout,
>> -    required this.composer,
>> -    required this.commonOps,
>> -  }) : _getDocumentLayout = getDocumentLayout;
>> +  EditContext(
>> +      {required this.editor,
>> +      required DocumentLayout Function() getDocumentLayout,
>> +      required this.composer,
>> +      required this.commonOps,
>> +      this.scrollController})
>>
>> Please end multiline declarations like this with a , so that we don't
>> shift the braces into the lines of parameters.
>> ------------------------------
>>
>> In super_editor/lib/src/core/edit_context.dart
>> <https://github.com/superlistapp/super_editor/pull/589#discussion_r884215636>
>> :
>>
>> > @@ -17,12 +18,15 @@ class EditContext {
>>    ///
>>    /// The [documentLayout] is passed as a [getDocumentLayout] callback that
>>    /// should return the current layout as it might change.
>> -  EditContext({
>> -    required this.editor,
>> -    required DocumentLayout Function() getDocumentLayout,
>> -    required this.composer,
>> -    required this.commonOps,
>> -  }) : _getDocumentLayout = getDocumentLayout;
>> +  EditContext(
>> +      {required this.editor,
>> +      required DocumentLayout Function() getDocumentLayout,
>> +      required this.composer,
>> +      required this.commonOps,
>> +      this.scrollController})
>> +      : _getDocumentLayout = getDocumentLayout;
>> +
>> +  final ScrollController? scrollController;
>>
>> This field should be documented, like the others. Also, since it's
>> declared last in the incoming parameter list, the reader would probably
>> expect the scroll controller to appear at the bottom of the declarations.
>> When consistency doesn't cost us anything, we should be consistent.
>> ------------------------------
>>
>> In super_editor/lib/src/default_editor/document_keyboard_actions.dart
>> <https://github.com/superlistapp/super_editor/pull/589#discussion_r884215958>
>> :
>>
>> > @@ -12,6 +12,62 @@ import 'document_input_keyboard.dart';
>>  import 'paragraph.dart';
>>  import 'text.dart';
>>
>> +ExecutionInstruction scrollWhenNavigationKeyPressed({
>>
>> I see that other actions aren't commented. That's probably an oversight.
>> These handlers should include clear explanation for why they exist, and
>> what they do.
>>
>> As for the name, I'm not sure that anyone is going to know what a
>> "navigation key" is. It's probably clearer to simply list the keys that are
>> relevant: scrollOnPageUpPageDownHomeAndEnd()
>> ------------------------------
>>
>> In super_editor/lib/src/default_editor/document_keyboard_actions.dart
>> <https://github.com/superlistapp/super_editor/pull/589#discussion_r884216024>
>> :
>>
>> > @@ -12,6 +12,62 @@ import 'document_input_keyboard.dart';
>>  import 'paragraph.dart';
>>  import 'text.dart';
>>
>> +ExecutionInstruction scrollWhenNavigationKeyPressed({
>> +  required EditContext editContext,
>> +  required RawKeyEvent keyEvent,
>> +}) {
>> +  //the super_editor doesn't always have a scroll controller
>>
>> I think that it always should have one, or at least always have a
>> ScrollPosition. In any event, there should always be a scrollable that
>> surrounds a document.
>> ------------------------------
>>
>> In super_editor/lib/src/default_editor/document_keyboard_actions.dart
>> <https://github.com/superlistapp/super_editor/pull/589#discussion_r884216159>
>> :
>>
>> > +}) {
>> +  //the super_editor doesn't always have a scroll controller
>> +  if (editContext.scrollController == null) {
>> +    return ExecutionInstruction.continueExecution;
>> +  }
>> +
>> +  if (keyEvent.logicalKey.keyId < LogicalKeyboardKey.end.keyId ||
>> +      keyEvent.logicalKey.keyId > LogicalKeyboardKey.pageUp.keyId) {
>> +    return ExecutionInstruction.continueExecution;
>> +  }
>> +
>> +  final scrollController = editContext.scrollController!;
>> +
>> +  double? jumpTo;
>> +
>> +  //end key or fn-arrowDn (on Mac)
>>
>> I see a number of comments that appear to restate the key comparison in
>> the if-statements. I don't think these comments are telling us more than
>> the if-statements that follow. The interesting details are where you're
>> jumping. For example, within the first if-branch, it might nice to say //
>> The user pressed the END key, scroll to the bottom of the document.
>> ------------------------------
>>
>> In super_editor/lib/src/default_editor/document_keyboard_actions.dart
>> <https://github.com/superlistapp/super_editor/pull/589#discussion_r884216223>
>> :
>>
>> > +  final scrollController = editContext.scrollController!;
>> +
>> +  double? jumpTo;
>> +
>> +  //end key or fn-arrowDn (on Mac)
>> +  if (keyEvent.logicalKey == LogicalKeyboardKey.end) {
>> +    jumpTo = scrollController.position.maxScrollExtent;
>> +    //home key or fn-arrowUp (on Mac)
>> +  } else if (keyEvent.logicalKey == LogicalKeyboardKey.home) {
>> +    jumpTo = scrollController.position.minScrollExtent;
>> +    //pgDn key or fn-arrowDn (on Mac)
>> +  } else if (keyEvent.logicalKey == LogicalKeyboardKey.pageDown) {
>> +    final nextJump = scrollController.offset + scrollController.position.extentInside;
>> +
>> +    jumpTo =
>> +        nextJump < scrollController.position.maxScrollExtent ? nextJump : scrollController.position.maxScrollExtent;
>>
>> I think this line can be replaced with a call to min() when you set
>> nextJump. Also, it's unclear why one thing is called nextJump and the
>> other is called jumpTo. I'm guessing you did that because you needed a
>> temporary variable. In this case you don't a temporary variable, but if you
>> did, it would be preferable to choose a name that explains why you need 2
>> variables, e.g., scrollOffsetOnePageDown. That name implies that there
>> may be a difference between "one page down" and "jump to"
>> ------------------------------
>>
>> In super_editor/lib/src/default_editor/document_keyboard_actions.dart
>> <https://github.com/superlistapp/super_editor/pull/589#discussion_r884216250>
>> :
>>
>> > +  if (keyEvent.logicalKey == LogicalKeyboardKey.end) {
>> +    jumpTo = scrollController.position.maxScrollExtent;
>> +    //home key or fn-arrowUp (on Mac)
>> +  } else if (keyEvent.logicalKey == LogicalKeyboardKey.home) {
>> +    jumpTo = scrollController.position.minScrollExtent;
>> +    //pgDn key or fn-arrowDn (on Mac)
>> +  } else if (keyEvent.logicalKey == LogicalKeyboardKey.pageDown) {
>> +    final nextJump = scrollController.offset + scrollController.position.extentInside;
>> +
>> +    jumpTo =
>> +        nextJump < scrollController.position.maxScrollExtent ? nextJump : scrollController.position.maxScrollExtent;
>> +    //pgUp key or fn-arrowUp (on Mac)
>> +  } else if (keyEvent.logicalKey == LogicalKeyboardKey.pageUp) {
>> [...]

2022-06-19 17:16 UTC, closed without merging